services:
  postgres:
    image: postgres:16
    container_name: test-database
    environment:
      POSTGRES_DB: connectPro_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: